import { useEffect, useState } from 'react'
import { createMixedCirclePost, interactWithMixedCirclePost, loadMixedCirclePosts } from '../services/circlePostService.js'

function MixedCirclePosts({ isAdmin }) {
  const [posts, setPosts] = useState([]); const [canPost, setCanPost] = useState(false); const [canInteract, setCanInteract] = useState(false); const [body, setBody] = useState(''); const [comments, setComments] = useState({}); const [error, setError] = useState('')
  async function load() { const data = await loadMixedCirclePosts(); setPosts(data.posts); setCanPost(data.canPost); setCanInteract(data.canInteract) }
  useEffect(() => { load().catch((nextError) => setError(nextError.message)) }, [])
  async function post(event) { event.preventDefault(); try { const data = await createMixedCirclePost(body); setPosts(data.posts); setBody('') } catch (nextError) { setError(nextError.message) } }
  async function react(id) { try { await interactWithMixedCirclePost(id, 'react'); await load() } catch (nextError) { setError(nextError.message) } }
  async function comment(event, id) { event.preventDefault(); try { await interactWithMixedCirclePost(id, 'comment', comments[id] || ''); setComments((current) => ({ ...current, [id]: '' })); await load() } catch (nextError) { setError(nextError.message) } }
  return <section className="workflow-card stacked-card"><div><p className="eyebrow">Mixed Circle updates</p><h4>Admin announcements</h4><p>All Mixed Circle members can view posts. Premium members can comment and react.{!canInteract ? ' Upgrade to premium to interact.' : ''}</p>{error ? <p className="error-message" role="alert">{error}</p> : null}</div>{(isAdmin || canPost) ? <form className="inline-form" onSubmit={post}><label htmlFor="mixed-post">Post an update</label><textarea id="mixed-post" value={body} onChange={(event) => setBody(event.target.value)} required /><button className="button">Publish post</button></form> : null}<div className="message-list">{posts.length ? posts.map((post) => <article className="message-bubble" key={post.id}><p><strong>{post.authorName}</strong></p><p>{post.body}</p><small>{new Date(post.createdAt).toLocaleString()}</small><div className="action-row">{canInteract ? <button className="button secondary" type="button" onClick={() => react(post.id)}>{post.reacted ? 'Remove reaction' : 'React'} ({post.reactionCount})</button> : <span>{post.reactionCount} reactions</span>}</div>{post.comments.map((comment) => <p key={comment.id}><strong>{comment.authorName}:</strong> {comment.body}</p>)}{canInteract ? <form className="inline-form" onSubmit={(event) => comment(event, post.id)}><input value={comments[post.id] || ''} onChange={(event) => setComments((current) => ({ ...current, [post.id]: event.target.value }))} placeholder="Write a comment" required /><button className="button secondary">Comment</button></form> : null}</article>) : <p className="save-status">No admin posts yet.</p>}</div></section>
}
export default MixedCirclePosts
